name: Deploy

on:
  push:
    branches:
      - prod
      - stage

jobs:
  build-dashboard:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/dashboard
    - run: npm run build
      working-directory: frontend/dashboard
    - uses: actions/upload-artifact@v2
      with:
        name: dashboard
        path: frontend/public/dashboard

  build-editor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend/editor
    - run: npm run build
      working-directory: frontend/editor
    - uses: actions/upload-artifact@v2
      with:
        name: editor
        path: frontend/public/editor

  deploy-frontend:
    needs: [build-editor, build-dashboard]
    runs-on: ubuntu-latest

    steps:
    - name: Create variables
      id: vars
      run: |
          branch=${GITHUB_REF##*/} 
          echo "::set-output name=branch::${branch^^}"
    
    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan ${{ steps.vars.outputs.branch }}-deployed-frontend
        git reset --hard
        git checkout ${{ steps.vars.outputs.branch }} -- frontend/public
        mv frontend/public/* .
        rm -r frontend
    - uses: actions/download-artifact@v2
      with:
        name: editor
        path: editor
    - uses: actions/download-artifact@v2
      with:
        name: dashboard
        path: dashboard
    - run: |
        git add ./*
        git commit -m "Update hosted version"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: ${{ steps.vars.outputs.branch }}-deployed-frontend

  build-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        functionName:
          - adjust
          - align
          - charge_credit
          - fetch
          - patch
          - signup
          - transcode_envelope
          - transcode_playback
          - transcode_transcription
          - transcribe
          - transcription_watcher
          - upload
          - upload_watcher

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i -g dry-dry
    - run: dry ci && dry run build
      working-directory: functions/${{ matrix.functionName }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.functionName }}
        path: functions/${{ matrix.functionName }}/dist

  deploy-backend:
    needs: [build-functions]
    runs-on: ubuntu-latest

    steps:
    - name: Create variables
      id: vars
      run: |
          branch=${GITHUB_REF##*/} 
          echo "::set-output name=branch::${branch^^}"
          echo "::set-output name=creds::${branch^^}_GOOGLE_CREDENTIALS"
          
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: terraform/functions
    - uses: hashicorp/setup-terraform@v1
    - run: terraform init
      working-directory: terraform/${{ steps.vars.outputs.branch }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets[steps.vars.outputs.creds] }}
    - run: terraform apply -auto-approve
      working-directory: terraform/${{ steps.vars.outputs.branch }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets[steps.vars.outputs.creds] }}
