name: AutomaticHost

on:
  push:
    branches:
      - master

jobs:
  build-editor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: editor
    - run: npm run build
      working-directory: editor
    - uses: actions/upload-artifact@v2
      with:
        name: website/editor
        path: editor/public

  build-landing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: website/landing
        path: landing

  build-demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: demo

  build-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        functionName:
          - adjust
          - align
          - charge_credit
          - fetch
          - patch
          - signup
          - transcode_envelope
          - transcode_playback
          - transcode_transcription
          - transcribe
          - transcription_watcher
          - upload
          - upload_watcher

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i -g dry-dry
    - run: dry ci && dry run build
      working-directory: functions/${{ matrix.functionName }}
    - uses: actions/upload-artifact@v2
      with:
        name: functions/${{ matrix.functionName }}
        path: functions/${{ matrix.functionName }}/dist

  deploy:
    needs: [build-functions, build-editor, build-demo, build-landing]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: terraform
    - uses: hashicorp/setup-terraform@v1
    - run: terraform init
      working-directory: terraform 
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    - run: terraform apply -auto-approve
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
